export const DEFAULT_MAX_PANE_WIDTH = 80;
export const MIN_MAX_PANE_WIDTH = 40;
export const MAX_MAX_PANE_WIDTH = 300;
export const SHIFT_MAX_PANE_WIDTH_STEP = 10;

export const DEFAULT_MIN_PANE_WIDTH = 50;
export const MIN_MIN_PANE_WIDTH = MIN_MAX_PANE_WIDTH;
export const MAX_MIN_PANE_WIDTH = MAX_MAX_PANE_WIDTH;
export const SHIFT_MIN_PANE_WIDTH_STEP = SHIFT_MAX_PANE_WIDTH_STEP;
